# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'gwap' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for gwap
  pod 'GoogleSignIn'

  target 'gwapTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'gwap-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for gwap-tvOS

  target 'gwap-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
